name = "PlayingCards"
uuid = "b23e55cc-b8be-42d4-99aa-dbf7daa45c92"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.0.1"


[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleRandom = "a6525b86-64cd-54fa-8f65-62fc48bdc0e8"

[compat]
julia = "1"
SimpleRandom = "0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
