name = "PlayingCards52"
uuid = "c2ceccfa-fa3a-4f0d-8d5f-27465c1854bf"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.1"


[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
